apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app1
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30012
  selector:
    app: {{ .Release.Name }}-app1

