---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  name: "{{ .Release.Name}}-deployment"
  labels:
    {{- include "my.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "my.selector.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "my.labels" . | indent 8 }}
    spec:
      containers:
      - name: "nginx"
        image: "nginx:1.7.9"
        ports:
        - containerPort: 80