---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-data
data:
  host.app1: {{ .Release.Name }}-app1
  host.redis: {{ .Release.Name }}-redis
  host.app2: {{ .Release.Name }}-app2
